using DataFlow.Core.Models;

namespace DataFlow.Core.Interfaces;

public interface IDataFlowApiClient
{
    Task<IReadOnlyList<ProjectDto>> ListProjectsAsync(CancellationToken ct = default);
    Task<ProjectDto> CreateProjectAsync(ProjectCreateRequest request, CancellationToken ct = default);
    Task<ProjectDto> GetProjectAsync(int id, CancellationToken ct = default);
    Task DeleteProjectAsync(int id, CancellationToken ct = default);
    Task<ProjectSummaryDto> GetProjectSummaryAsync(int id, CancellationToken ct = default);

    Task<IReadOnlyList<DatasetDto>> ListDatasetsAsync(int projectId, CancellationToken ct = default);
    Task<DatasetDto> UploadDatasetAsync(int projectId, string filePath, IProgress<double>? progress = null, CancellationToken ct = default);
    Task<ChartDataDto> GetChartDataAsync(int datasetId, CancellationToken ct = default);
    Task<ReviveSessionDto> ReviveSessionAsync(int datasetId, CancellationToken ct = default);

    Task<IReadOnlyList<DashboardDto>> ListDashboardsAsync(int projectId, CancellationToken ct = default);
    Task<DashboardDto> GetDashboardAsync(int id, CancellationToken ct = default);
    Task<DashboardDto> CreateDashboardAsync(DashboardCreateRequest request, CancellationToken ct = default);
    Task<DashboardDto> UpdateDashboardAsync(int id, DashboardUpdateRequest request, CancellationToken ct = default);
    Task DeleteDashboardAsync(int id, CancellationToken ct = default);

    Task DeleteDatasetAsync(int id, CancellationToken ct = default);

    Task<IReadOnlyList<ChatSessionDto>> ListChatSessionsAsync(int projectId, CancellationToken ct = default);
    Task<ChatSessionDto> CreateChatSessionAsync(ChatSessionCreateRequest request, CancellationToken ct = default);
    Task UpdateChatSessionTitleAsync(int sessionId, string title, CancellationToken ct = default);
    Task DeleteChatSessionAsync(int sessionId, CancellationToken ct = default);
    Task<IReadOnlyList<ChatMessageDto>> GetChatMessagesAsync(int sessionId, CancellationToken ct = default);
    Task AddChatMessageAsync(int sessionId, ChatMessageCreateRequest request, CancellationToken ct = default);

    Task<ChatResponseDto> SendChatAsync(string message, string? sessionId, string? filePath, string? historyJson, CancellationToken ct = default);

    Task<InsightsReportDto?> GetInsightsAsync(string aiSessionId, CancellationToken ct = default);
    Task<DashboardLayoutDocument?> AutoGenerateDashboardAsync(string aiSessionId, CancellationToken ct = default);
    Task<IReadOnlyDictionary<string, object>> GetRealtimeStreamTypesAsync(CancellationToken ct = default);

    // Enterprise endpoints
    Task<EnterpriseHealthDto?> GetEnterpriseHealthAsync(CancellationToken ct = default);
    Task<SemanticModelDto?> GetSemanticModelAsync(string aiSessionId, CancellationToken ct = default);
    Task<DashboardLayoutDocument?> BuildEnterpriseDashboardAsync(string aiSessionId, string layoutType = "executive", CancellationToken ct = default);
    Task<DashboardThemesDto?> GetDashboardThemesAsync(CancellationToken ct = default);
    Task<ShareDashboardResultDto?> ShareDashboardAsync(string dashboardJson, CancellationToken ct = default);
    Task<DashboardLayoutDocument?> GetSharedDashboardAsync(string token, CancellationToken ct = default);
    Task<ChartDataDto?> GetAdvancedChartsAsync(string aiSessionId, CancellationToken ct = default);
    Task<string?> ExportDashboardReportAsync(string dashboardJson, CancellationToken ct = default);
    Task<CacheStatsDto?> GetCacheStatsAsync(CancellationToken ct = default);

    Task<bool> HealthCheckAsync(CancellationToken ct = default);
}
