using DataFlow.Core.Enums;
using DataFlow.Core.Interfaces;
using DataFlow.Core.Navigation;
using DataFlow.Core.Themes;
using DataFlow.UI.Controls;
using DataFlow.UI.Controls.Styled;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;

namespace DataFlow.UI.Views;

/// <summary>Enterprise API endpoint audit — verifies all /enterprise routes.</summary>
public sealed class EnterpriseAuditView : UserControl, INavigationAware
{
    private readonly IDataFlowApiClient _api;
    private readonly INavigationService _navigation;
    private readonly RichTextBox _log;
    private string? _aiSessionId;
    private int _projectId;

    public EnterpriseAuditView(IServiceProvider services)
    {
        _api = services.GetRequiredService<IDataFlowApiClient>();
        _navigation = services.GetRequiredService<INavigationService>();
        BackColor = Color.FromArgb(17, 19, 24);
        Dock = DockStyle.Fill;

        var header = new Panel { Dock = DockStyle.Top, Height = 52, BackColor = Color.FromArgb(26, 29, 40), Padding = new Padding(12) };
        var back = new Button { Text = "← Back", FlatStyle = FlatStyle.Flat, ForeColor = Color.WhiteSmoke, AutoSize = true };
        back.Click += (_, _) => _navigation.Navigate(NavigationArgs.For(AppView.ProjectDetail, _projectId));
        var run = new AccentButton { Text = "Run audit", Location = new Point(120, 8), Width = 100 };
        run.Click += async (_, _) => await RunAuditAsync();
        header.Controls.AddRange([back, run]);

        _log = new RichTextBox
        {
            Dock = DockStyle.Fill,
            ReadOnly = true,
            BackColor = Color.FromArgb(22, 25, 34),
            ForeColor = Color.FromArgb(200, 205, 215),
            Font = new Font("Consolas", 9f),
            BorderStyle = BorderStyle.None
        };

        Controls.Add(_log);
        Controls.Add(header);
    }

    public void OnNavigatedTo(NavigationArgs args)
    {
        if (args.ProjectId is int pid) _projectId = pid;
        _ = InitSessionAsync();
    }

    private async Task InitSessionAsync()
    {
        var datasets = await _api.ListDatasetsAsync(_projectId);
        var ds = datasets.FirstOrDefault();
        if (ds != null)
        {
            var revive = await _api.ReviveSessionAsync(ds.Id);
            _aiSessionId = revive.AiSessionId;
        }
        AppendLine("Enterprise API audit ready. Click Run audit.");
    }

    private async Task RunAuditAsync()
    {
        _log.Clear();
        await Check("GET /enterprise/health", async () =>
        {
            var h = await _api.GetEnterpriseHealthAsync();
            return h?.Modules.Count > 0 ? $"modules: {h.Modules.Count}" : "no data";
        });

        await Check("GET /enterprise/realtime/types", async () =>
        {
            var t = await _api.GetRealtimeStreamTypesAsync();
            return $"{t.Count} stream type(s)";
        });

        await Check("GET /enterprise/dashboard/themes", async () =>
        {
            var t = await _api.GetDashboardThemesAsync();
            return t?.Themes.Count > 0 ? string.Join(", ", t.Themes.Take(3)) : "none";
        });

        await Check("GET /enterprise/cache/stats", async () =>
        {
            var c = await _api.GetCacheStatsAsync();
            return c == null ? "n/a" : $"sessions={c.Sessions}";
        });

        if (string.IsNullOrEmpty(_aiSessionId))
        {
            AppendLine("\n⚠ Skipping session endpoints — no AI session (upload dataset first).");
            return;
        }

        await Check("POST /enterprise/semantic-model", async () =>
        {
            var m = await _api.GetSemanticModelAsync(_aiSessionId!);
            return m == null ? "failed" : $"entities={m.Entities.Count}";
        });

        await Check("POST /enterprise/insights", async () =>
        {
            var i = await _api.GetInsightsAsync(_aiSessionId!);
            return i == null ? "failed" : $"{i.TotalInsights} insights";
        });

        await Check("POST /enterprise/auto-dashboard", async () =>
        {
            var d = await _api.AutoGenerateDashboardAsync(_aiSessionId!);
            return d == null ? "failed" : $"{d.Widgets.Count} widgets";
        });

        await Check("POST /enterprise/dashboard/build", async () =>
        {
            var d = await _api.BuildEnterpriseDashboardAsync(_aiSessionId!, "executive");
            return d == null ? "failed" : $"{d.Widgets.Count} widgets";
        });

        await Check("POST /enterprise/advanced-charts", async () =>
        {
            var c = await _api.GetAdvancedChartsAsync(_aiSessionId!);
            return c == null ? "failed" : $"{c.Headers.Count} columns";
        });

        var sampleJson = JsonConvert.SerializeObject(new { title = "Audit", widgets = Array.Empty<object>() });
        await Check("POST /enterprise/reports/export", async () =>
        {
            var j = await _api.ExportDashboardReportAsync(sampleJson);
            return string.IsNullOrEmpty(j) ? "failed" : $"{j.Length} chars";
        });

        await Check("POST /enterprise/dashboard/share", async () =>
        {
            var s = await _api.ShareDashboardAsync(sampleJson);
            return s == null ? "failed" : $"token={s.Token}";
        });

        AppendLine("\n✓ Audit complete.");
    }

    private async Task Check(string name, Func<Task<string>> action)
    {
        try
        {
            var result = await action();
            AppendLine($"✓ {name} → {result}");
        }
        catch (Exception ex)
        {
            AppendLine($"✗ {name} → {ex.Message}");
        }
    }

    private void AppendLine(string text)
    {
        _log.AppendText(text + Environment.NewLine);
        _log.ScrollToCaret();
    }
}
